### ISSUE TITLE
ReusableBufferCache is empty.

### ISSUE THREAD

**Issue by uAliFurkanY** [oguzeroglu/Rhubarb#1]
Output:

```
P:\Programs\JS\Projects\Rhubarb-test\node_modules\rhubarb-js\build\Rhubarb.js:29
    throw new Error("ReusableBufferCache is empty.");
    ^

Error: ReusableBufferCache is empty.
    at ReusableBufferCache.get (P:\Programs\JS\Projects\Rhubarb-test\node_modules\rhubarb-js\build\Rhubarb.js:29:11)
    at Protocol.setParameterToBuffer (P:\Programs\JS\Projects\Rhubarb-test\node_modules\rhubarb-js\build\Rhubarb.js:121:52)
    at Rhubarb.send (P:\Programs\JS\Projects\Rhubarb-test\node_modules\rhubarb-js\build\Rhubarb.js:475:14)
    at Server.onClientConnected (P:\Programs\JS\Projects\Rhubarb-test\index.js:36:10)
    at Server.<anonymous> (P:\Programs\JS\Projects\Rhubarb-test\node_modules\rhubarb-js\build\Rhubarb.js:370:12)
    at WebSocketServer.emit (events.js:210:5)
    at P:\Programs\JS\Projects\Rhubarb-test\node_modules\ws\lib\websocket-server.js:98:18
    at WebSocketServer.completeUpgrade (P:\Programs\JS\Projects\Rhubarb-test\node_modules\ws\lib\websocket-server.js:331:5)
    at WebSocketServer.handleUpgrade (P:\Programs\JS\Projects\Rhubarb-test\node_modules\ws\lib\websocket-server.js:255:10)
    at Server.upgrade (P:\Programs\JS\Projects\Rhubarb-test\node_modules\ws\lib\websocket-server.js:97:16)
```

**Comment by oguzeroglu** [comment]
Can you provide a bit more context please?

Sharing your JS code that generated this error would be a good idea.

**Comment by uAliFurkanY** [comment]
```js
Rhubarb.onClientConnected(function (clientID) {
	let hashedId = sha256(clientID);
	online.players[hashedId] = {
		id: clientID,
		name: "Player" + random(1, 1000000),
		position: [random(), random()]
	};
	console.log(online.players[hashedId]);
	Rhubarb.send("sendId", {
		id: hashedId,
		secret: clientID
	}, clientID);
});
```


Protocols:
```json
{
	"getPos": {
		"id": "char_64"
	},
	"getPosAccepted": {
		"x": "numerical",
		"y": "numerical"
	},
	"sendId": {
		"id": "char_64",
		"secret": "char_36"
	}
}
```

The error occurs in `Rhubarb.send`

**Comment by oguzeroglu** [comment]
Thanks, I'm on it :)

**Comment by oguzeroglu** [comment]
Thanks for the report! The issue turned out to be a bug and I fixed it, released a new version.

Make sure to download the latest version for your client: https://github.com/oguzeroglu/Rhubarb/releases

Also published a new npm package so make sure to update rhubarb-js to v1.2.0
